### ISSUE TITLE
可以爬青岛的吗

### ISSUE THREAD

**Issue by X-Mars** [lanbing510/LianJiaSpider#2]
我把所有的
bj.lianjia.com
改成了
qd.lianjia.com
现在有报错，如下
`/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/mars/git/LianJiaSpider/LianJiaSpider.py
<urllib2.Request instance at 0x102cf1f38>
404
Not Found
http://qd.lianjia.com/?ticket=ST-7736156-tIILbXMnsuLyfc4PUyfx-www.lianjia.com
Date: Sun, 27 Nov 2016 10:08:06 GMT
LB_HEADER: aws-1a-lj-nginx00.ares.lianjia.com
Server: Tengine/2.2.0
Content-Length: 0
Connection: Close

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 371 of the file /Users/mars/git/LianJiaSpider/LianJiaSpider.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 774 of the file /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
timed out
爬下了 市南 区全部的小区信息
timed out
爬下了 市北 区全部的小区信息
爬下了 李沧 区全部的小区信息
爬下了 崂山 区全部的小区信息
Traceback (most recent call last):
爬下了 四方 区全部的小区信息
  File "/Users/mars/git/LianJiaSpider/LianJiaSpider.py", line 377, in <module>
done
    exception_spider(db_cj)
  File "/Users/mars/git/LianJiaSpider/LianJiaSpider.py", line 341, in exception_spider
    excep_list=exception_read()
  File "/Users/mars/git/LianJiaSpider/LianJiaSpider.py", line 326, in exception_read
    f=open('log.txt','r')
IOError: [Errno 2] No such file or directory: 'log.txt'

Process finished with exit code 1`

**Comment by X-Mars** [comment]
我把
LianJiaLogIn.py
中的65行
username
修改为
mobile
404的报错没了
---------
运行LianJiaSpider.py后，提示如下

```log
/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/mars/git/LianJiaSpider/LianJiaSpider.py
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 371 of the file /Users/mars/git/LianJiaSpider/LianJiaSpider.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 774 of the file /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
爬下了 市南 区全部的小区信息
爬下了 市北 区全部的小区信息
爬下了 李沧 区全部的小区信息
爬下了 四方 区全部的小区信息
爬下了 崂山 区全部的小区信息
爬下了 城阳 区全部的小区信息
done
all done ^_^

Process finished with exit code 0
```
但是db文件是空的。
求解

**Comment by lanbing510** [comment]
链家每个城市的模板不一样，需要根据相应的城市做相应的更改~

**Comment by X-Mars** [comment]
ok
我研究下
